import { z } from 'zod'

const materialSchema = z.object({
  id: z.string(),
  nameKey: z.string(),
  rarity: z.enum(['common', 'uncommon', 'rare', 'epic', 'legendary', 'event']),
  value: z.number().int().nonnegative(),
  normalWeight: z.number().nonnegative(),
  harvestWeight: z.number().nonnegative(),
})

const balanceSchema = z.object({
  version: z.string(),
  physics: z.object({
    fixedStep: z.number().positive(),
    gravity: z.number().positive(),
    ballRadius: z.number().positive(),
    ballRestitution: z.number().min(0).max(1),
    wallRestitution: z.number().min(0).max(1),
    friction: z.number().nonnegative(),
    maxSpeed: z.number().positive(),
    stallSpeed: z.number().positive(),
    stallTimeoutMs: z.number().positive(),
    unstickDistance: z.number().positive(),
    unstickImpulse: z.number().positive(),
    launcherMinForce: z.number().positive(),
    launcherMaxForce: z.number().positive(),
    chargeDurationMs: z.number().positive(),
    flipperSpeed: z.number().positive(),
    flipperImpulse: z.number().positive(),
    bumperImpulse: z.number().positive(),
    sprintMultiplier: z.number().positive(),
    rejectMultiplier: z.number().positive(),
    slingshotImpulse: z.number().positive(),
    meteorImpulse: z.number().positive(),
    inspectionImpulse: z.number().positive(),
    rescueImpulse: z.number().positive(),
  }),
  rules: z.object({
    comboTimeoutMs: z.number().positive(),
    hitDebounceMs: z.number().positive(),
    inspectionCooldownMs: z.number().positive(),
    inspectionCaptureMs: z.number().positive(),
    meteorCaptureMs: z.number().positive(),
    endingAnimationMs: z.number().positive(),
    logicTickMs: z.number().positive(),
    autoSaveMs: z.number().positive(),
    resumeCountdownSeconds: z.number().int().positive(),
  }),
  acceptance: z.array(z.object({ rating: z.string(), multiplier: z.number(), weight: z.number() })),
  events: z.record(
    z.string(),
    z.object({
      durationMs: z.number().nonnegative(),
      cooldownMs: z.number().nonnegative(),
      weight: z.number().nonnegative(),
      category: z.enum(['positive', 'risk', 'fun']),
      waitTimeoutMs: z.number().nonnegative().optional(),
    })
  ),
  materials: z.record(z.string(), z.array(materialSchema)),
  title: z.object({
    weights: z.object({
      currency: z.number(),
      duration: z.number(),
      technique: z.number(),
      special: z.number(),
    }),
    currencyMax: z.number().positive(),
    durationCurve: z.array(z.tuple([z.number(), z.number()])),
    ranges: z.array(z.object({ min: z.number(), key: z.string() })),
  }),
})

/** 游戏唯一的数值平衡配置。策划调整手感与经济时只修改此对象。 */
export const BALANCE = balanceSchema.parse({
  version: '1.1.0',
  physics: {
    fixedStep: 1 / 120,
    gravity: 27,
    ballRadius: 18,
    ballRestitution: 0.72,
    wallRestitution: 0.5,
    friction: 0.18,
    maxSpeed: 62,
    stallSpeed: 0.45,
    stallTimeoutMs: 1500,
    unstickDistance: 44,
    unstickImpulse: 5.5,
    launcherMinForce: 22,
    launcherMaxForce: 66,
    chargeDurationMs: 1400,
    flipperSpeed: 18,
    flipperImpulse: 22,
    bumperImpulse: 17,
    sprintMultiplier: 1.35,
    rejectMultiplier: 1.7,
    slingshotImpulse: 15,
    meteorImpulse: 20,
    inspectionImpulse: 18,
    rescueImpulse: 24,
  },
  rules: {
    comboTimeoutMs: 2500,
    hitDebounceMs: 180,
    inspectionCooldownMs: 10_000,
    inspectionCaptureMs: 1200,
    meteorCaptureMs: 400,
    endingAnimationMs: 700,
    logicTickMs: 50,
    autoSaveMs: 5000,
    resumeCountdownSeconds: 3,
  },
  acceptance: [
    { rating: 'qualified', multiplier: 1.2, weight: 1 },
    { rating: 'excellent', multiplier: 1.3, weight: 1 },
    { rating: 'perfect', multiplier: 1.4, weight: 1 },
  ],
  events: {
    overtime: {
      durationMs: 7000,
      cooldownMs: 10_000,
      weight: 12,
      category: 'risk',
      waitTimeoutMs: 12_000,
    },
    wanted: { durationMs: 10_000, cooldownMs: 10_000, weight: 16, category: 'fun' },
    inspection: { durationMs: 12_000, cooldownMs: 10_000, weight: 16, category: 'positive' },
    sprint: { durationMs: 8000, cooldownMs: 10_000, weight: 16, category: 'positive' },
    excuses: { durationMs: 12_000, cooldownMs: 10_000, weight: 12, category: 'risk' },
    rareHarvest: {
      durationMs: 10_000,
      cooldownMs: 10_000,
      weight: 18,
      category: 'positive',
    },
    meteorHarvest: {
      durationMs: 15_000,
      cooldownMs: 10_000,
      weight: 10,
      category: 'positive',
    },
    rescueReturn: { durationMs: 0, cooldownMs: 10_000, weight: 8, category: 'fun' },
  },
  materials: {
    farm: [
      ['cupAroma', 'material.cupAroma', 'common', 10, 36, 20],
      ['lingGrass', 'material.lingGrass', 'common', 20, 26, 22],
      ['puffOrchid', 'material.puffOrchid', 'uncommon', 30, 18, 20],
      ['roundFlower', 'material.roundFlower', 'rare', 50, 10, 16],
      ['jingleFruit', 'material.jingleFruit', 'epic', 80, 6, 13],
      ['cloudFruit', 'material.cloudFruit', 'legendary', 120, 4, 9],
    ].map(([id, nameKey, rarity, value, normalWeight, harvestWeight]) => ({
      id,
      nameKey,
      rarity,
      value,
      normalWeight,
      harvestWeight,
    })),
    pond: [
      ['glassesFish', 'material.glassesFish', 'common', 10, 44, 25],
      ['eyelinerFish', 'material.eyelinerFish', 'uncommon', 20, 28, 25],
      ['lipstickFish', 'material.lipstickFish', 'rare', 40, 16, 22],
      ['pufferFish', 'material.pufferFish', 'epic', 70, 8, 18],
      ['perfumeFish', 'material.perfumeFish', 'legendary', 120, 4, 10],
    ].map(([id, nameKey, rarity, value, normalWeight, harvestWeight]) => ({
      id,
      nameKey,
      rarity,
      value,
      normalWeight,
      harvestWeight,
    })),
    nest: [
      ['leafStone', 'material.leafStone', 'common', 10, 44, 25],
      ['flyingPearl', 'material.flyingPearl', 'uncommon', 20, 28, 25],
      ['treasurePearl', 'material.treasurePearl', 'rare', 40, 16, 22],
      ['featherStone', 'material.featherStone', 'epic', 80, 8, 18],
      ['treasureStone', 'material.treasureStone', 'legendary', 140, 4, 10],
    ].map(([id, nameKey, rarity, value, normalWeight, harvestWeight]) => ({
      id,
      nameKey,
      rarity,
      value,
      normalWeight,
      harvestWeight,
    })),
    meteor: [
      ['brightMeteor', 'material.brightMeteor', 'common', 50, 52, 38],
      ['forestMeteor', 'material.forestMeteor', 'uncommon', 100, 28, 28],
      ['ghostMeteor', 'material.ghostMeteor', 'rare', 180, 14, 20],
      ['honeyMeteor', 'material.honeyMeteor', 'epic', 320, 6, 13],
      ['giantMeteor', 'material.giantMeteor', 'event', 1200, 0, 1],
    ].map(([id, nameKey, rarity, value, normalWeight, harvestWeight]) => ({
      id,
      nameKey,
      rarity,
      value,
      normalWeight,
      harvestWeight,
    })),
  },
  title: {
    weights: { currency: 0.45, duration: 0.3, technique: 0.2, special: 0.05 },
    currencyMax: 15_000,
    durationCurve: [
      [30, 5],
      [60, 12],
      [180, 28],
      [360, 45],
      [600, 60],
      [1200, 78],
      [2400, 92],
      [3600, 100],
    ],
    ranges: [
      { min: 95, key: 'director' },
      { min: 85, key: 'manager' },
      { min: 73, key: 'collector' },
      { min: 60, key: 'boss' },
      { min: 45, key: 'overtimeAdmin' },
      { min: 30, key: 'supervisor' },
      { min: 15, key: 'intern' },
      { min: 0, key: 'escapeHelper' },
    ],
  },
})

export type BalanceConfig = z.infer<typeof balanceSchema>
export type MaterialConfig = z.infer<typeof materialSchema>
