import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/tests/browser/midi-editor-page.html')
  await expect(page.locator('.editor-toolbar')).toBeVisible()
})

test('拍号下拉可以点击、滚动，并将更改写入编辑会话', async ({ page }) => {
  const numerator = page.locator('.toolbar-meter').first()
  await numerator.click()
  const popup = page.locator('.ant-select-dropdown:visible')
  await popup.locator('.ant-select-item-option').filter({ hasText: /^3$/ }).click({ timeout: 3000 })
  await expect(numerator).toContainText('3')
  await page.getByRole('button', { name: /撤销/ }).click()
  await expect(numerator).toContainText('4')
  await numerator.click()
  await popup.hover()
  await page.mouse.wheel(0, 500)
  await expect(popup.locator('.ant-select-item-option').filter({ hasText: /^16$/ })).toBeVisible()
  await popup.locator('.ant-select-item-option').filter({ hasText: /^16$/ }).click()
  await expect(numerator).toContainText('16')
  await page.locator('.toolbar-meter').nth(1).click()
  await popup.locator('.ant-select-item-option').filter({ hasText: /^8$/ }).click()
  await expect(page.locator('.toolbar-meter').nth(1)).toContainText('8')
  await page.locator('.toolbar-snap').click()
  await popup
    .locator('.ant-select-item-option')
    .filter({ hasText: /^1\/8$/ })
    .click()
  await expect(page.locator('.toolbar-snap')).toContainText('1/8')
})

test('全屏编辑填满窗口，切换保留项目，退出编辑恢复全局播放条', async ({ page }) => {
  await expect(page.locator('.global-music-player')).toBeAttached()
  await expect(page.locator('.global-music-player')).toBeHidden()
  const name = page.locator('.midi-editor-name input, input.midi-editor-name')
  await name.fill('全屏测试项目')
  await name.blur()
  const before = await page.locator('.midi-editor-body').boundingBox()
  await page.getByRole('button', { name: '全屏编辑', exact: true }).click()
  await expect(page.locator('.window-title-bar')).toBeHidden()
  const bounds = await page.locator('.midi-editor-page').boundingBox()
  expect(bounds).toMatchObject({ x: 0, y: 0, width: 1100, height: 850 })
  expect((await page.locator('.midi-editor-body').boundingBox())!.height).toBeGreaterThan(
    before!.height
  )
  await expect(name).toHaveValue('全屏测试项目')
  await page.locator('.toolbar-meter').first().click()
  await page
    .locator('.ant-select-dropdown:visible .ant-select-item-option')
    .filter({ hasText: /^3$/ })
    .click()
  await page.getByRole('button', { name: '退出全屏编辑', exact: true }).click()
  await expect(page.locator('.window-title-bar')).toBeVisible()
  await expect(name).toHaveValue('全屏测试项目')
  await expect(page.locator('.toolbar-meter').first()).toContainText('3')
  await page.getByRole('button', { name: '全屏编辑', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.window-title-bar')).toBeVisible()
  await page.getByRole('button', { name: /撤销/ }).click()
  await page.getByRole('button', { name: /撤销/ }).click()
  await page.getByRole('button', { name: /取\s*消/ }).click()
  await expect(page.locator('.global-music-player')).toBeVisible()
})
