import { test, expect } from '@playwright/test'

test('独立工作区首键录制、停止后编辑、应用以及一次撤销', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  await expect(dialog.getByText('按下第一个映射键开始')).not.toBeVisible()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await expect(dialog.getByText('按下第一个映射键开始')).toBeVisible()
  await page.keyboard.down('a')
  await page.waitForTimeout(150)
  await page.keyboard.up('a')
  await dialog.getByRole('button', { name: '停止录制', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('0')
  await dialog.getByRole('button', { name: '应用到音轨', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('1')
  await page.getByRole('button', { name: '主项目撤销' }).click()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('0')
})

test('取消隔离、输入控件不录音、窄窗口保持键盘可读', async ({ page }) => {
  await page.setViewportSize({ width: 760, height: 650 })
  await page.goto('/tests/browser/track-recorder.html')
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  const applyBounds = await dialog
    .getByRole('button', { name: '应用到音轨', exact: true })
    .boundingBox()
  expect(applyBounds!.y + applyBounds!.height).toBeLessThanOrEqual(650)
  const key = dialog.locator('.key.clickable').first()
  expect(
    await key.locator('.pitch-label').evaluate((el) => parseFloat(getComputedStyle(el).fontSize))
  ).toBeGreaterThanOrEqual(12)
  await dialog.getByRole('combobox').first().focus()
  await page.keyboard.press('a')
  await page.keyboard.press('Escape')
  await expect(dialog.getByRole('button', { name: '应用到音轨', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await page.keyboard.down('a')
  await page.waitForTimeout(80)
  await page.keyboard.up('a')
  await dialog.getByRole('button', { name: '停止录制', exact: true }).click()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('0')
})

test('首键后失焦暂停，映射的 Tab 与 Space 可录制且不触发页面导航', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await page.keyboard.down('Tab')
  await page.waitForTimeout(80)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.keyboard.up('Tab')
  await expect(dialog.getByRole('button', { name: '继续录制', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '继续录制', exact: true }).click()
  await page.keyboard.down('Space')
  await page.waitForTimeout(80)
  await page.keyboard.up('Space')
  await page.keyboard.press('Escape')
  await dialog.getByRole('button', { name: '应用到音轨', exact: true }).click()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('2')
})

test('恢复独立录制草稿；应用后删除失败只重试清理且不再次提交', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.evaluate(() => window.recorderFixture.seedDraft(false))
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  await dialog.getByRole('button', { name: '继续录制草稿', exact: true }).click()
  await page.evaluate(() => window.recorderFixture.failDelete(true))
  await dialog.getByRole('button', { name: '应用到音轨', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('disk-delete')
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('1')
  await expect(dialog.getByRole('button', { name: '开始录制', exact: true })).not.toBeEnabled()
  await page.evaluate(() => window.recorderFixture.failDelete(false))
  await dialog.getByRole('button', { name: '应用到音轨', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(await page.evaluate(() => window.recorderFixture.applyCount())).toBe(1)
})

test('放弃期间不再排入周期草稿，慢保存完成后不会复活已删除的草稿', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await page.keyboard.down('a')
  await page.waitForTimeout(80)
  await page.keyboard.up('a')
  await dialog.getByRole('button', { name: '停止录制', exact: true }).click()
  await page.evaluate(() => window.recorderFixture.deferDrafts(true))
  await expect.poll(() => page.evaluate(() => window.recorderFixture.pendingDrafts())).toBe(1)
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  await page.waitForTimeout(1100)
  await page.evaluate(() => window.recorderFixture.finishDraft())
  await expect(dialog).not.toBeVisible()
  expect(await page.evaluate(() => window.recorderFixture.pendingDrafts())).toBe(0)
  expect(await page.evaluate(() => window.recorderFixture.draftCount())).toBe(0)
})

test('暂停追加后改重录选段不会删除之前的音符', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.evaluate(() => window.recorderFixture.seedExisting())
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  await dialog.locator('div[tabindex="0"]').nth(1).focus()
  await page.keyboard.press('ControlOrMeta+a')
  await dialog.getByRole('button', { name: '重录选中片段', exact: true }).click()
  // 先设定选段，再回到接着录；选区与区间仍保留。
  await dialog.locator('.ant-select').nth(1).click()
  await page
    .locator('.ant-select-dropdown:visible .ant-select-item-option')
    .filter({ hasText: '接着录' })
    .click()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await page.keyboard.down('a')
  await page.waitForTimeout(80)
  await page.keyboard.up('a')
  await dialog.getByRole('button', { name: '暂停录制', exact: true }).click()
  await dialog.getByRole('button', { name: '重录选中片段', exact: true }).click()
  await dialog.getByRole('button', { name: '应用到音轨', exact: true }).click()
  await expect(page.locator('[data-testid="host-note-count"]')).toHaveText('2')
})

test('鼠标按住后移出映射键立即释放，不等到鼠标抬起', async ({ page }) => {
  await page.goto('/tests/browser/track-recorder.html')
  await page.getByRole('button', { name: '键盘录制' }).click()
  const dialog = page.getByRole('dialog').first()
  const key = dialog.locator('.key.clickable').first()
  await dialog.getByRole('button', { name: '开始录制', exact: true }).click()
  await key.hover()
  const box = (await key.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await expect(key).toHaveClass(/active/)
  await page.mouse.move(box.x + box.width + 80, box.y + box.height + 40)
  await expect(key).not.toHaveClass(/active/)
  await page.mouse.up()
})
